name: "Deploy"

on:
  workflow_run:
    workflows: ["Elixir CI"]
    types: [completed]

jobs:
  on-success:
    runs-on: ubuntu-latest
    environment: deploy
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - name: execute deploy script on server
      uses: appleboy/ssh-action@v1.1.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        script: whoami
